name: Keepalive CI

on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * *'

jobs:
  keepalive:
    name: Connect to StackOverflow
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

    - name: Keepalive StackOverflow
      run: |
        curl 'https://stackoverflow.com/users/2928168/emi' \
          -H 'authority: stackoverflow.com' \
          -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
          -H 'accept-language: ca-ES,ca;q=0.9,en;q=0.8,es;q=0.7' \
          -H 'cache-control: max-age=0' \
          -H "${SO_COOKIE}" \
          -H 'referer: https://stackoverflow.com/users/2928168/emi' \
          -H 'sec-ch-ua: "Not:A-Brand";v="99", "Chromium";v="112"' \
          -H 'sec-ch-ua-mobile: ?0' \
          -H 'sec-ch-ua-platform: "Linux"' \
          -H 'sec-fetch-dest: document' \
          -H 'sec-fetch-mode: navigate' \
          -H 'sec-fetch-site: same-origin' \
          -H 'sec-fetch-user: ?1' \
          -H 'upgrade-insecure-requests: 1' \
          -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' \
          --compressed
      env:
        SO_COOKIE: ${{ secrets.SO_COOKIE }}
